# Generated by Django 4.2.1 on 2023-05-25 12:37

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='choices_list',
            field=django_mysql.models.ListCharField(models.IntegerField(), max_length=255, size=None),
        ),
    ]
